name = "rolldoradoapp-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradoapp.es"
HMAC_KEY = "6e46ac66ddce7a16e908df80e57bccb0931b43b31eefdb6ceffd52102150990d"
COOKIE_NAME = "4oq"
PLAY_PATH = "visit-site"
BUTTON_ID = "p65a587344f787d79e0c33a3e817faf59"
GATE_SALT = "a9ce95e6bd983dde"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "k1yk"
CTA_SELECTOR = ".play-button"
